services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: mse_qdrant
    networks:
      - public-network
    ports:
      - 6334:6333
    expose:
      - 6334
    volumes:
      - ./qdrant_data:/qdrant/storage

  mse_pg_dev:
    image: postgres:latest
    container_name: mse_pg_dev
    networks:
      - public-network
    restart: always
    volumes:
      - mse_pg_data_dev:/var/lib/postgresql/data/
    ports:
      - 5555:5432
    environment:
      - POSTGRES_DB=mse_db_dev
      - POSTGRES_USER=mse_pg_dev
      - POSTGRES_PASSWORD=mse_pg_dev

  backend:
    build: . 
    container_name: mse_api
    networks:
      - public-network
    restart: on-failure
    command: bash -c "alembic upgrade head && python3 -m src.main"
    ports:
      - 8686:8686
    volumes:
      - ./alembic:/app/alembic
      - ./src:/app/src
      - ./menu_data:/app/menu_data
      - ./hf_cache:/app/cache:rw
    depends_on:
      - mse_pg_dev
      - qdrant
    env_file: .env
    environment:
      - PG_HOST=mse_pg_dev
      - PG_PORT=5432
      - FASTEMBED_CACHE_DIR=/app/cache
      - HF_HOME=/app/cache

volumes:
  qdrant_data:
  mse_pg_data_dev:

networks:
  public-network:
    external: true
    name: mse_net